/**
 * AGENTS.md scaffolding: every generated project ships a repo-scoped guide for coding agents
 * (the AGENTS.md cross-agent standard), plus a CLAUDE.md bridge file (Claude Code reads
 * CLAUDE.md; `@AGENTS.md` imports the shared file). Content is a trimmed, warehouse-tailored
 * version of the authoring delta guide — baked at scaffold time and versioned with the engine
 * release, same freshness model as the `sqlanvilCoreVersion` pin.
 */

export interface IAgentsMdOptions {
  /** bigquery | postgres | supabase | mysql */
  warehouse: string;
  /** The project's default dataset/schema (used in the intro text). */
  defaultDataset: string;
  /** Engine version stamped in the header comment. */
  version: string;
  /** True for `migrate-dataform` output — appends the converted-project addendum. */
  converted?: boolean;
}

/** Claude Code reads CLAUDE.md, not AGENTS.md — this one-line import bridges the two. */
export function claudeMdBridgeContents(): string {
  return "@AGENTS.md\n";
}

export function agentsMdContents(options: IAgentsMdOptions): string {
  const { warehouse, defaultDataset, version, converted } = options;
  const isPostgresLike = warehouse === "postgres" || warehouse === "supabase";
  const isSupabase = warehouse === "supabase";
  const isMysql = warehouse === "mysql";

  const sections: string[] = [];

  sections.push(`<!-- generated by sqlanvil ${version} — this file is yours; edit freely -->

# SQLAnvil project — guide for coding agents

This is a **SQLAnvil** data project (warehouse: **${warehouse}**, default dataset/schema:
\`${defaultDataset}\`). SQLAnvil is a fork of Dataform, so Dataform instincts are mostly
right: \`.sqlx\` files, \`config {}\` blocks, \`\${ref()}\`, \`\${self()}\`, declarations,
assertions, tags, incremental tables, and \`pre_operations\`/\`post_operations\` all work the
same. The rules below are where the differences bite.

## The essentials

- The CLI is \`sqlanvil\` (\`npm i -g @sqlanvil/cli\`) — there is no \`dataform\` CLI and no
  npm scripts in this project.
- \`workflow_settings.yaml\` pins \`sqlanvilCoreVersion:\` — sqlanvil's OWN SemVer line, NOT
  \`dataformCoreVersion:\`.
- Credentials live in the gitignored \`.df-credentials.json\`. Never commit it; never put
  secrets in \`workflow_settings.yaml\`.
- The statement separator in \`operations\` / \`pre_operations\` / \`post_operations\` is
  \`---\` on its own line — NEVER \`;\`. Dollar-quoted bodies (\`$$ … ; … $$\`) survive
  intact. A \`table\`/\`view\` model body is exactly ONE \`SELECT\` — no \`---\`.
- Procedures, functions, triggers, grants, extensions → \`type: "operations"\` (there is no
  dedicated action type).
- Two different \`uniqueKey\`s: top-level \`uniqueKey\` on an incremental is the merge/upsert
  key; \`assertions: { uniqueKey }\` generates a data-quality assertion. They are independent.
- Always reference tables with \`\${ref("name")}\` — never hardcoded paths. Declare external
  tables (\`type: "declaration"\`) before ref'ing them.
- Document every table: \`description:\` + \`columns: {}\` compile to real comments.

## Commands

\`\`\`bash
sqlanvil compile .
sqlanvil validate . --credentials .df-credentials.json   # planner-checks the whole DAG without executing — run this before every run
sqlanvil run . --credentials .df-credentials.json
sqlanvil run . --credentials .df-credentials.json --actions <name> --include-deps
sqlanvil test . --credentials .df-credentials.json
\`\`\`

\`target/\` holds compile/run artifacts (queryable via \`sqlanvil query\`/\`inspect\`) — keep
it gitignored.`);

  if (isPostgresLike) {
    sections.push(`## ${isSupabase ? "Supabase/PostgreSQL" : "PostgreSQL"} specifics

- \`.df-credentials.json\` is a FLAT object with exactly \`host port database user password
  sslMode defaultSchema\` — not nested under a key, not \`username\`/\`databaseName\`/\`ssl\`.${
      isSupabase
        ? `
  Use the Session pooler host (\`aws-…pooler.supabase.com\`, user \`postgres.<project-ref>\`,
  port 5432): the direct \`db.<ref>.supabase.co\` host is IPv6-only and fails on most networks.`
        : ""
    }
- Storage, indexes, and partitioning are first-class in the \`postgres: {}\` config block —
  never hand-roll \`CREATE INDEX\` or \`SET (fillfactor …)\` in \`post_operations\`.
- Index \`method\` is a NUMERIC enum (\`BTREE=0, HASH=1, GIN=2, GIST=3, BRIN=4\`) — omit it
  for btree; the string \`method: "btree"\` fails the config check. \`opclass\` is a single
  string, not an array.
- No BigQuery-isms: \`bigquery: {}\`, \`partitionBy\`, \`clusterBy\`, \`OPTIONS(...)\` — use
  \`postgres: { partition: {...}, indexes: [...] }\` (partition \`kind\`: RANGE=0, LIST=1,
  HASH=2).
- Materialized views: \`type: "view", materialized: true\` (+ optional \`postgres: {
  refreshPolicy: "on_dependency_change", noData, indexes }\`). Default is drop+recreate each
  run; in-place refresh does not pick up definition changes.
- One-time DDL on incrementals (e.g. \`ADD PRIMARY KEY\`) must be wrapped in
  \`\${when(!incremental(), \\\`…\\\`)}\` — an unwrapped \`post_operations\` block re-runs on
  EVERY append and errors the second time.
- Read tables in OTHER warehouses via named \`connections:\` in \`workflow_settings.yaml\`
  plus a \`connection:\`-tagged declaration with \`columnTypes\` in POSTGRES types — scaffold
  it with \`sqlanvil introspect <connection> <schema.table>\`. Never hand-write FDW/foreign
  tables.${
      isSupabase
        ? `
- Supabase extras: the \`supabase: {}\` block (\`enableRls\`, \`vectors\`) and dedicated
  action types \`rlsPolicy\`, \`realtimePublication\`, \`vectorIndex\`. \`enableRls\` only
  flips RLS on — declare policies via \`rlsPolicy\` actions.`
        : ""
    }`);
  }

  if (isMysql) {
    sections.push(`## MySQL/MariaDB specifics (several Postgres rules INVERT here)

- \`.df-credentials.json\` is a FLAT object with exactly \`host port database user password
  sslMode\` — no \`defaultSchema\` (MySQL's "schema" IS the database).
- Use the \`mysql: {}\` config block for indexes, table options (\`engine\`, \`charset\`,
  \`rowFormat\`), and partitioning — never \`postgres: {}\` (wrong dialect, silently ignored).
- An incremental's \`uniqueKey\` compiles to \`INSERT … ON DUPLICATE KEY UPDATE\` and the
  adapter AUTO-CREATES the matching unique index — do not add your own PK/unique index for
  the merge.
- \`materialized: true\` is an emulated snapshot (drop + CTAS each run), not a native
  matview; no \`refreshPolicy\`/\`noData\`.
- Backtick-quote identifiers in raw DDL; never \`DELIMITER\` (client-only directive — the
  \`---\` separator already keeps \`;\` bodies intact).
- A mysql warehouse cannot read cross-warehouse \`connections:\` (single write warehouse;
  MySQL works as a SOURCE for a Postgres/Supabase project, not the other way).`);
  }

  if (converted) {
    sections.push(`## This project was converted from Dataform

- Work the to-do list in \`migration-report.md\` (machine-readable twin:
  \`migration-report.json\`). Inline \`SQLANVIL-MIGRATE:\` markers flag every rewritten or
  questionable spot.
- \`sqlanvil validate\` is the completion loop — converge on all-PASS.
- The original Dataform repo was read-only during conversion and remains the rollback path.`);
  }

  sections.push(`---

Docs: https://sqlanvil.com/docs (agent bundle: https://sqlanvil.com/llms.txt) · Full
authoring skill: \`npx skills add SQLAnvil/agent-skills\` · Hosted CI/scheduling:
https://app.sqlanvil.com (remote MCP server at \`/api/mcp\`).`);

  return sections.join("\n\n") + "\n";
}
