import { expect } from "chai";
import * as fs from "fs-extra";
import * as os from "os";
import * as path from "path";

import {
  TodoClass,
  connectionNameFor,
  convertTarget,
  findConfigBlock,
  migrateDataform,
  parseSqlxConfig
} from "sa/cli/api/commands/migrate_dataform";
import { suite, test } from "sa/testing";

suite("migrate-dataform", () => {
  function fixtureProject(): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "sqlanvil-migrate-src-"));
    const write = (rel: string, contents: string) => {
      const full = path.join(dir, rel);
      fs.mkdirsSync(path.dirname(full));
      fs.writeFileSync(full, contents);
    };

    write(
      "workflow_settings.yaml",
      ["defaultLocation: US", "defaultProject: acme-analytics", "defaultDataset: dataform", "defaultAssertionDataset: dataform_assertions", "dataformCoreVersion: 3.0.61"].join("\n")
    );
    // Credentials that must NEVER be copied.
    write(".df-credentials.json", `{"projectId":"x"}`);
    write("service_account_key.json", `{"private_key":"x"}`);
    write(".env", "SECRET=x");
    write("compile_output.json", "{}");

    // Declarations: literal database, projectConfig expression, and a description.
    write(
      "definitions/sources/ods/customers.sqlx",
      `config {
    type: "declaration",
    database: dataform.projectConfig.defaultDatabase,
    schema: "ods",
    name: "customers",
}
`
    );
    write(
      "definitions/sources/raw/events.sqlx",
      `config {
    type: "declaration",
    database: "other-project",
    schema: "raw_events",
    name: "events",
    description: "Raw event stream",
}
`
    );
    // A declaration in a schema that is ALSO a target schema (overlap warning).
    write(
      "definitions/sources/ods/flags.sqlx",
      `config { type: "declaration", schema: "ods", name: "flags" }
`
    );

    // Target with the BigQuery-isms.
    write(
      "definitions/output/daily.sqlx",
      `config {
  type: "table",
  schema: "ods",
  bigquery: {
    partitionBy: "sale_date",
    clusterBy: ["region"]
  },
  tags: ["daily"]
}

SELECT
  SAFE_CAST(amount AS NUMERIC) AS amount,
  SAFE_DIVIDE(a, b) AS ratio,
  CURRENT_DATE() AS today
FROM \${ref("customers")}
QUALIFY ROW_NUMBER() OVER (PARTITION BY id ORDER BY ts DESC) = 1
`
    );
    write(
      "definitions/output/fqn.sqlx",
      `config { type: "view" }
SELECT * FROM \`acme-analytics.ods.legacy_table\`
`
    );
    // Clean target — must come through byte-identical apart from nothing.
    write(
      "definitions/output/clean.sqlx",
      `config { type: "view", schema: "reports" }
SELECT id, name FROM \${ref("customers")}
`
    );
    // Config with an orphaned separator comma after the bigquery block, plus a database
    // qualifier, plus a js{} block whose contents must NOT receive inline markers.
    write(
      "definitions/output/tricky.sqlx",
      `config {
  type: "table",
  database: dataform.projectConfig.defaultDatabase,
  bigquery: {
    clusterBy: ["store_zip"]
  }
,
  columns: {
    id: "the id"
  }
}

js {
  const helper = \`SELECT SAFE_CAST(x AS INT64) FROM t\`;
}

SELECT 1 AS id
`
    );

    // A .js definition using the compile global.
    write(
      "definitions/operations/dynamic.js",
      `operate("dyn", { disabled: dataform.projectConfig.schemaSuffix !== "prod" }).queries(() => "SELECT 1");
`
    );
    // includes helper emitting BigQuery SQL.
    write(
      "includes/functions.js",
      `const domainFromEmail = (email) => \`split(\${email}, '@')[SAFE_OFFSET(1)]\`;
module.exports = { domainFromEmail };
`
    );
    return dir;
  }

  function snapshot(dir: string): Map<string, string> {
    const map = new Map<string, string>();
    const walk = (rel: string) => {
      for (const e of fs.readdirSync(path.join(dir, rel), { withFileTypes: true })) {
        const r = rel ? `${rel}/${e.name}` : e.name;
        if (e.isDirectory()) walk(r);
        else map.set(r, fs.readFileSync(path.join(dir, r), "utf8"));
      }
    };
    walk("");
    return map;
  }

  test("converts the fixture: connections, declarations, markers, report — source untouched", async () => {
    const src = fixtureProject();
    const before = snapshot(src);
    const out = fs.mkdtempSync(path.join(os.tmpdir(), "sqlanvil-migrate-out-"));
    fs.rmdirSync(out); // migrateDataform accepts a missing dir

    const report = await migrateDataform({ srcDir: src, outDir: out, coreVersion: "9.9.9" });

    // THE guarantee: byte-identical source afterwards.
    expect(snapshot(src)).deep.equals(before);

    // Agent guidance generated for the CONVERTED project (fixture ships none of its own).
    const agentsMd = fs.readFileSync(path.join(out, "AGENTS.md"), "utf8");
    expect(agentsMd).to.contain("generated by sqlanvil 9.9.9");
    expect(agentsMd).to.contain("warehouse: **supabase**");
    expect(agentsMd).to.contain("converted from Dataform");
    expect(agentsMd).to.contain("migration-report.md");
    expect(fs.readFileSync(path.join(out, "CLAUDE.md"), "utf8")).equals("@AGENTS.md\n");
    expect(report.files.filter(f => f.action === "generated").map(f => f.file)).to.have.members([
      "AGENTS.md",
      "CLAUDE.md",
      "scripts/introspect_all.sh"
    ]);

    // workflow_settings: supabase + pinned core + both connections.
    const settings = fs.readFileSync(path.join(out, "workflow_settings.yaml"), "utf8");
    expect(settings).to.contain("warehouse: supabase");
    expect(settings).to.contain("defaultDataset: dataform");
    expect(settings).to.contain("sqlanvilCoreVersion: 9.9.9");
    expect(settings).to.contain("bq_acme_analytics:");
    expect(settings).to.contain("bq_other_project:");
    expect(settings).to.contain("mode: runner-extract");
    expect(settings).to.contain("billingProject: acme-analytics");
    expect(settings).to.not.contain("defaultProject");
    expect(settings).to.not.contain("defaultLocation");

    // Declarations rewritten onto connections, with the introspect TODO.
    const decl = fs.readFileSync(path.join(out, "definitions/sources/ods/customers.sqlx"), "utf8");
    expect(decl).to.contain('connection: "bq_acme_analytics"');
    expect(decl).to.contain('schema: "ods"');
    expect(decl).to.contain('name: "customers"');
    expect(decl).to.contain("sqlanvil introspect bq_acme_analytics ods.customers");
    expect(decl).to.not.contain("database:");
    const decl2 = fs.readFileSync(path.join(out, "definitions/sources/raw/events.sqlx"), "utf8");
    expect(decl2).to.contain('description: "Raw event stream"');
    expect(decl2).to.contain('connection: "bq_other_project"');
    expect(decl2).to.contain('schema: "raw_events"');

    // Ready-to-run introspect script: one CONCRETE command per declaration (the report used
    // to show only per-connection templates — acuantia migrate test finding #19).
    const script = fs.readFileSync(path.join(out, "scripts/introspect_all.sh"), "utf8");
    expect(script).to.contain(
      'sqlanvil introspect bq_acme_analytics "ods.customers" --output "definitions/sources/ods/customers.sqlx"'
    );
    expect(script).to.contain('sqlanvil introspect bq_other_project');
    expect(script).to.not.contain("<dataset>");
    // Resilient: failures are collected and summarized, not fatal on the first
    // stale declaration (acuantia migrate finding: dropped table aborted all 881).
    expect(script).to.not.contain("set -e");
    expect(script).to.contain('run sqlanvil introspect bq_acme_analytics "ods.customers"');
    expect(script).to.contain("failures=$((failures + 1))");
    expect(script).to.contain('if [ "$failures" -gt 0 ]; then');
    const reportMd = fs.readFileSync(path.join(out, "migration-report.md"), "utf8");
    expect(reportMd).to.contain("scripts/introspect_all.sh");

    // Target rewrites + markers.
    const daily = fs.readFileSync(path.join(out, "definitions/output/daily.sqlx"), "utf8");
    // SAFE_CAST keeps its NULL-on-bad-input behaviour via pg_input_is_valid. Rewriting it to a
    // bare CAST (as this did before) turns a silent NULL into a run-time failure in code the
    // converter itself wrote — and projects rely on the NULL for sources with known-bad values.
    expect(daily).to.contain(
      "(case when pg_input_is_valid((amount)::text, 'numeric') then (amount)::numeric end)",
    );
    expect(daily).to.not.match(/SAFE_CAST\s*\(/); // the explanatory marker may name SAFE_CAST
    expect(daily).to.contain("CURRENT_DATE AS today");
    // SAFE_DIVIDE is now rewritten rather than flagged — it needs the arguments, which the
    // per-line lexical rules cannot reach.
    expect(daily).to.contain("(a / nullif(b, 0))");
    expect(daily).to.not.match(/SAFE_DIVIDE\s*\(/);
    expect(daily).to.contain("-- SQLANVIL-MIGRATE: QUALIFY");
    // bigquery block commented out with a config-context marker.
    expect(daily).to.contain("// SQLANVIL-MIGRATE: BigQuery-only setting");
    expect(daily).to.contain("//   bigquery: {");
    expect(daily).to.not.match(/^\s*bigquery: \{/m);
    // tags survive.
    expect(daily).to.contain('tags: ["daily"]');

    const fqn = fs.readFileSync(path.join(out, "definitions/output/fqn.sqlx"), "utf8");
    expect(fqn).to.contain("-- SQLANVIL-MIGRATE: backticked BigQuery FQN");

    const clean = fs.readFileSync(path.join(out, "definitions/output/clean.sqlx"), "utf8");
    expect(clean).to.not.contain("SQLANVIL-MIGRATE");

    // Orphan comma swallowed, database: commented, js{} contents untouched by markers.
    const tricky = fs.readFileSync(path.join(out, "definitions/output/tricky.sqlx"), "utf8");
    expect(tricky).to.contain("//   database:");
    expect(tricky).to.not.match(/^\s*,\s*$/m); // no orphaned separator comma outside comments
    expect(tricky).to.match(/^\/\/\s*,\s*$/m); // it was commented out instead
    // In-line rewrites still apply inside js{} (safe); only marker LINES are suppressed there.
    // SAFE_CAST inside a js template gets the same guard, and INT64 becomes bigint — a helper
    // that builds SQL is still SQL, and leaving it alone was invisible until run time.
    expect(tricky).to.contain(
      "(case when pg_input_is_valid((x)::text, 'bigint') then (x)::bigint end)",
    );
    expect(tricky.split("js {")[1].split("}")[0]).to.not.contain("SQLANVIL-MIGRATE");
    expect(tricky).to.contain('id: "the id"'); // columns survived the comma handling

    // Compile-global rename in .js + includes.
    const dyn = fs.readFileSync(path.join(out, "definitions/operations/dynamic.js"), "utf8");
    expect(dyn).to.contain("sqlanvil.projectConfig.schemaSuffix");
    // The code (after the summary block, whose note names the old global) is fully renamed.
    expect(dyn.split("*/").pop()).to.not.contain("dataform.projectConfig");
    // .js files get one top-of-file summary block, never inline markers.
    const inc = fs.readFileSync(path.join(out, "includes/functions.js"), "utf8");
    expect(inc.startsWith("/* SQLANVIL-MIGRATE")).equals(true);
    expect(inc.split("*/")[1]).to.not.contain("SQLANVIL-MIGRATE");
    // Shared helpers build SQL in template literals, so they need the dialect pass as much as a
    // .sqlx does — `split(x, d)[SAFE_OFFSET(n)]` here failed two views on every run of a real
    // migration while looking like an unconverted .sqlx problem.
    expect(inc).to.contain("(string_to_array(${email}, '@'))[2]");
    expect(inc.split("*/")[1]).to.not.contain("SAFE_OFFSET");

    // Credentials and artifacts never copied.
    for (const secret of [".df-credentials.json", "service_account_key.json", ".env", "compile_output.json"]) {
      expect(fs.existsSync(path.join(out, secret)), secret).equals(false);
      expect(report.skippedForSafety).to.include(secret);
    }

    // Report shape.
    expect(report.inventory.byType.declaration).equals(3);
    expect(report.connections.map(c => c.name)).deep.equals([
      "bq_acme_analytics",
      "bq_other_project"
    ]);
    expect(report.connections[0].declarationCount).equals(2);
    expect(report.connections[0].datasets).deep.equals(["ods"]);
    expect(report.overlappingSchemas).deep.equals(["ods"]);
    const flaggedTargets = report.files.filter(f => f.action === "target" && f.status === "flagged");
    expect(flaggedTargets.map(f => f.file)).to.include("definitions/output/daily.sqlx");
    expect(fs.existsSync(path.join(out, "migration-report.md"))).equals(true);
    expect(fs.existsSync(path.join(out, "migration-report.json"))).equals(true);
    const md = fs.readFileSync(path.join(out, "migration-report.md"), "utf8");
    expect(md).to.contain("Schemas that are BOTH source and target");
  });

  test("targetWarehouse bigquery: tooling swap — SQL/bigquery:{}/declarations untouched, settings carried", async () => {
    const src = fixtureProject();
    const before = snapshot(src);
    const out = fs.mkdtempSync(path.join(os.tmpdir(), "sqlanvil-migrate-bq-"));
    fs.rmdirSync(out);

    const report = await migrateDataform({
      srcDir: src,
      outDir: out,
      coreVersion: "9.9.9",
      targetWarehouse: "bigquery"
    });

    // Source still byte-identical.
    expect(snapshot(src)).deep.equals(before);
    expect(report.targetWarehouse).equals("bigquery");

    // Settings: same warehouse — project/location carried, dataset case kept, no warehouse
    // key (BigQuery is core's implicit default), no connections.
    const settings = fs.readFileSync(path.join(out, "workflow_settings.yaml"), "utf8");
    expect(settings).to.contain("defaultProject: acme-analytics");
    expect(settings).to.contain("defaultLocation: US");
    expect(settings).to.contain("defaultDataset: dataform");
    expect(settings).to.contain("defaultAssertionDataset: dataform_assertions");
    expect(settings).to.contain("sqlanvilCoreVersion: 9.9.9");
    expect(settings).to.not.contain("warehouse:");
    expect(settings).to.not.contain("connections:");
    expect(report.connections).to.have.length(0);

    // Targets: BigQuery SQL and bigquery:{} config pass through byte-identical.
    const daily = fs.readFileSync(path.join(out, "definitions/output/daily.sqlx"), "utf8");
    expect(daily).equals(before.get("definitions/output/daily.sqlx"));
    expect(daily).to.contain("bigquery: {");
    expect(daily).to.contain("SAFE_CAST(");
    expect(daily).to.contain("QUALIFY");
    expect(daily).to.not.contain("SQLANVIL-MIGRATE");

    // Declarations: no connection rewrite; only the compile-global rename applies anywhere.
    const decl = fs.readFileSync(path.join(out, "definitions/sources/ods/customers.sqlx"), "utf8");
    expect(decl).to.contain("database: sqlanvil.projectConfig.defaultDatabase");
    expect(decl).to.not.contain("connection:");
    expect(decl).to.not.contain("columnTypes");
    const events = fs.readFileSync(path.join(out, "definitions/sources/raw/events.sqlx"), "utf8");
    expect(events).equals(before.get("definitions/sources/raw/events.sqlx"));

    // The compile-global rename still lands in .js files; includes stay warning-free.
    const dyn = fs.readFileSync(path.join(out, "definitions/operations/dynamic.js"), "utf8");
    expect(dyn).to.contain("sqlanvil.projectConfig.schemaSuffix");
    expect(report.warnings.filter(w => w.includes("includes"))).to.have.length(0);

    // Mode-aware report + the converted-project AGENTS.md.
    const reportMd = fs.readFileSync(path.join(out, "migration-report.md"), "utf8");
    expect(reportMd).to.contain("Same-warehouse conversion");
    expect(reportMd).to.not.contain("Source connections");
    expect(reportMd).to.contain("gcloud auth application-default login");
    const agentsMd = fs.readFileSync(path.join(out, "AGENTS.md"), "utf8");
    expect(agentsMd).to.contain("warehouse: **bigquery**");
    expect(agentsMd).to.contain("converted from Dataform");
  });

  test("refuses an output dir inside the source (and vice versa), and a non-empty output", async () => {
    const src = fixtureProject();
    for (const bad of [path.join(src, "out"), path.dirname(src)]) {
      try {
        await migrateDataform({ srcDir: src, outDir: bad });
        expect.fail("expected rejection");
      } catch (e) {
        expect((e as Error).message).to.match(/must not be inside|not empty/);
      }
    }
    const nonEmpty = fs.mkdtempSync(path.join(os.tmpdir(), "sqlanvil-migrate-ne-"));
    fs.writeFileSync(path.join(nonEmpty, "x.txt"), "x");
    try {
      await migrateDataform({ srcDir: src, outDir: nonEmpty });
      expect.fail("expected rejection");
    } catch (e) {
      expect((e as Error).message).to.contain("not empty");
    }
  });

  test("dataform.json projects convert too (legacy field names)", async () => {
    const src = fs.mkdtempSync(path.join(os.tmpdir(), "sqlanvil-migrate-dj-"));
    fs.writeFileSync(
      path.join(src, "dataform.json"),
      JSON.stringify({
        warehouse: "bigquery",
        defaultDatabase: "legacy-project",
        defaultSchema: "dataform_data",
        assertionSchema: "df_assertions",
        vars: { region: "us" }
      })
    );
    fs.mkdirsSync(path.join(src, "definitions"));
    fs.writeFileSync(
      path.join(src, "definitions/src.sqlx"),
      `config { type: "declaration", schema: "raw", name: "t" }\n`
    );
    const out = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "sqlanvil-migrate-djo-")), "out");
    const report = await migrateDataform({ srcDir: src, outDir: out });
    const settings = fs.readFileSync(path.join(out, "workflow_settings.yaml"), "utf8");
    expect(settings).to.contain("defaultDataset: dataform_data");
    expect(settings).to.contain("defaultAssertionDataset: df_assertions");
    expect(settings).to.contain("region: us");
    expect(fs.existsSync(path.join(out, "dataform.json"))).equals(false);
    expect(report.connections[0].project).equals("legacy-project");
  });

  test("config parsing helpers handle strings-with-braces and the defaultDatabase expression", () => {
    const source = `config {
  type: "table",
  description: "has { braces } inside",
}
SELECT 1`;
    const span = findConfigBlock(source)!;
    const parsed = parseSqlxConfig(span.body);
    expect(parsed.type).equals("table");
    expect(parsed.description).equals("has { braces } inside");

    const decl = parseSqlxConfig(
      `type: "declaration", database: dataform.projectConfig.defaultDatabase, schema: "s", name: "n"`
    );
    expect(decl.database).equals("<defaultDatabase>");
    expect(connectionNameFor("My-Proj")).equals("bq_my_proj");
  });

  test("call rewrites reach the arguments, and span lines", () => {
    const sql = (body: string) => convertTarget(`config { type: "view" }\n\n${body}\n`, false).content;

    // A per-line regex cannot see this call at all — and a real project writes it this way.
    expect(
      sql("select DATE_DIFF(\n  a,\n  b,\n  DAY\n) as days"),
    ).to.contain("(a::date - b::date)");

    // BigQuery's HOUR counts boundaries CROSSED. Truncating both sides is what makes the two
    // agree; dividing the raw interval is off by one whenever the minutes do not line up.
    expect(sql("select DATE_DIFF(a, b, HOUR) as h")).to.contain("date_trunc('hour', a)");

    expect(sql("select SAFE_DIVIDE(a, b) as r")).to.contain("(a / nullif(b, 0))");
    expect(sql("select DATE_SUB(CURRENT_DATE, interval 7 day) as d"))
      .to.contain("(CURRENT_DATE - interval '7 day')");
    expect(sql("select REGEXP_EXTRACT(f, '[^/]+$') as name"))
      .to.contain("substring(f from '[^/]+$')");

    // COLLATE(x, '') is a FUNCTION in BigQuery and a syntax error in PostgreSQL; an empty
    // collation means "strip", which is a no-op here.
    expect(sql("select COLLATE(name, '') as name")).to.contain("select name as name");

    // An EMPTY delimiter splits per character. PostgreSQL spells that NULL — an empty string
    // would return the whole input as one element and silently change the result.
    expect(sql("select SPLIT(sku, '') as chars")).to.contain("string_to_array(sku, NULL)");
    expect(sql("select SPLIT(v, ',') as parts")).to.contain("string_to_array(v, ',')");

    // 0-based → 1-based, and the call must be parenthesised: PostgreSQL will not subscript a
    // function result directly.
    expect(sql("select SPLIT(email, '@')[SAFE_OFFSET(1)] as domain"))
      .to.contain("(string_to_array(email, '@'))[2]");

    // Type names are renamed even without SAFE_CAST, or they arrive as `type "int64" does not
    // exist` at run time.
    expect(sql("select CAST(x AS INT64) as n")).to.contain("cast(x as bigint)");

    // Nested calls: the inner rewrite lands before the outer one reads its arguments.
    expect(sql("select SAFE_DIVIDE(CAST(a AS FLOAT64), b) as r"))
      .to.contain("(cast(a as double precision) / nullif(b, 0))");
  });

  test("call rewrites leave strings, comments and config alone", () => {
    const out = (body: string) => convertTarget(body, false).content;

    // A rule must not fire inside a string literal or a comment.
    const inString = out(`config { type: "view" }\n\nselect 'SAFE_DIVIDE(a, b)' as lit\n`);
    expect(inString).to.contain("'SAFE_DIVIDE(a, b)'");
    const inComment = out(`config { type: "view" }\n\n-- SAFE_DIVIDE(a, b)\nselect 1\n`);
    expect(inComment).to.contain("-- SAFE_DIVIDE(a, b)");

    // Config keys have their own handling; the dialect pass must not reach into the block.
    const inConfig = out(`config {\n  type: "view",\n  description: "uses SPLIT(x, y)"\n}\n\nselect 1\n`);
    expect(inConfig).to.contain('description: "uses SPLIT(x, y)"');

    // An unresolvable form is left for the report rather than half-rewritten.
    expect(out(`config { type: "view" }\n\nselect DATE_DIFF(a, b, MONTH) as m\n`))
      .to.contain("DATE_DIFF(a, b, MONTH)");
  });

  test("lexical rules: BigQuery quoting, raw strings, # comments, DAYOFWEEK", () => {
    const sql = (body: string) => convertTarget(`config { type: "view" }\n\n${body}\n`, false).content;

    // In BigQuery a backtick always quotes an identifier and a double quote always opens a
    // string — the exact opposite of PostgreSQL for the latter, which is why leaving them gives
    // `column "select" does not exist`.
    expect(sql("select `my col` from t")).to.contain('"my col"');
    expect(sql(`select * from t where kind in ("a", "b")`)).to.contain("in ('a', 'b')");

    // A qualified name is a reference to re-point, not a quoting fix — PostgreSQL has no third
    // naming level — so it is left for the report.
    expect(sql("select 1 from `proj.dataset.table`")).to.contain("`proj.dataset.table`");

    // PostgreSQL has no raw-string prefix and reads the r as a type name.
    expect(sql("select regexp_replace(x, r'\\s+', ' ') as y")).to.contain("'\\s+'");
    expect(sql("select regexp_replace(x, r'\\s+', ' ') as y")).to.not.contain("r'");

    // BigQuery accepts # line comments; PostgreSQL has only --.
    expect(sql("# a note\nselect 1")).to.contain("-- a note");

    // BigQuery numbers the week from 1 = Sunday, PostgreSQL's dow from 0 — so the + 1 keeps
    // existing comparisons against 1 and 7 meaning weekend.
    expect(sql("select EXTRACT(DAYOFWEEK FROM d) as dw"))
      .to.contain("(extract(dow from d) + 1)");

    // After AS a double-quoted token is an ALIAS, not a string. Converting `x as "key"` to
    // `x as 'key'` is not valid SQL anywhere, and quietly turns a column name into a literal.
    expect(sql('select attribute_code as "key" from t')).to.contain('as "key"');

    // Not inside a string or a comment.
    expect(sql("select 'a `b` c' as lit")).to.contain("'a `b` c'");
    expect(sql("-- keep `this`\nselect 1")).to.contain("-- keep `this`");
  });

  test("the report hands over a class-first to-do list an agent can work", async () => {
    const src = fs.mkdtempSync(path.join(os.tmpdir(), "sqlanvil-triage-src-"));
    const out = fs.mkdtempSync(path.join(os.tmpdir(), "sqlanvil-triage-out-"));
    fs.rmdirSync(out);
    fs.outputFileSync(path.join(src, "workflow_settings.yaml"), "defaultProject: p\ndefaultDataset: d\n");
    // Two constructs needing a decision, one mechanical, spread over two files — so the grouping
    // has something to collapse.
    fs.outputFileSync(
      path.join(src, "definitions/a.sqlx"),
      'config { type: "view" }\n\nselect STRUCT(1 as x) as s, GENERATE_UUID() as id, SAFE_DIVIDE(a, b) as r\n',
    );
    fs.outputFileSync(
      path.join(src, "definitions/b.sqlx"),
      'config { type: "view" }\n\nselect STRUCT(2 as y) as s from t QUALIFY row_number() over () = 1\n',
    );
    const report = await migrateDataform({ srcDir: src, outDir: out, coreVersion: "9.9.9" });

    const byId = new Map(report.todo.map((t: TodoClass) => [t.id, t]));
    // Grouped by construct, not by file: STRUCT appears in both files as ONE entry.
    expect(byId.get("struct")!.count).equals(2);
    expect(byId.get("struct")!.locations.map(l => l.file)).to.have.members([
      "definitions/a.sqlx",
      "definitions/b.sqlx",
    ]);

    // The distinction an agent needs: what it may do alone vs what to ask about.
    expect(byId.get("struct")!.owner).equals("needs-decision");
    expect(byId.get("qualify")!.owner).equals("mechanical");
    expect(byId.get("generate-uuid")!.postgres).equals("gen_random_uuid()");

    // Ordered worst-first so the list reads as a plan rather than an inventory.
    const severities = report.todo.map((t: TodoClass) => t.severity);
    expect(severities.indexOf("changes-meaning")).to.be.lessThan(
      severities.lastIndexOf("blocks-compile") + 1,
    );

    // Automatic rewrites are reported separately, for review rather than trust.
    expect(report.applied.length).to.be.greaterThan(0);

    const md = fs.readFileSync(path.join(out, "migration-report.md"), "utf8");
    expect(md).to.contain("## What is left to do");
    expect(md).to.contain("### Needs a decision");
    expect(md).to.contain("### Mechanical");
    expect(md).to.contain("- [ ] **STRUCT / ARRAY of STRUCT** — 2 site(s)");
    expect(md).to.contain("## Rewrites applied automatically");
  });

  test("COLLATE stripping and NOT ENFORCED constraints", () => {
    const sql = (body: string) => convertTarget(`config { type: "table" }\n\n${body}\n`, false).content;

    // BigQuery's COLLATE(x, spec) is a FUNCTION and PostgreSQL's is an operator taking a
    // collation NAME, so the function form is a syntax error outright. An empty spec means
    // "strip the collation", which is a no-op here — both spellings unwrap to x.
    expect(sql("select COLLATE(name, '') as name")).to.contain("select name as name");
    expect(sql("select name COLLATE '' as name")).to.contain("select name as name");

    // NOT ENFORCED is advisory in BigQuery and has no PostgreSQL equivalent. Translated and
    // commented: enforcing it silently would fail on data that has never been checked, and
    // dropping it silently would lose the declared model.
    const one = sql("select 1 as id\npost_operations {\n  ALTER TABLE ${self()} ADD PRIMARY KEY (id) NOT ENFORCED;\n}");
    expect(one).to.contain("-- ALTER TABLE ${self()} ADD PRIMARY KEY (id);");
    expect(one).to.not.match(/^\s*ALTER TABLE/m); // nothing left executable
    expect(one).to.contain("-- BigQuery declared the constraint below NOT ENFORCED");
    // The clause is gone from the SQL; the explanation names it on purpose.
    const executable = one.split("\n").filter(l => !/^\s*(--|\/\/)/.test(l));
    expect(executable.join("\n")).to.not.contain("NOT ENFORCED");

    // Multi-action form, and the DROP preamble is omitted — PostgreSQL has no DROP PRIMARY KEY,
    // so leaving it in would break the statement the moment someone uncommented it.
    const many = sql(
      "select 1 as id\npost_operations {\n  ALTER TABLE t\n    DROP PRIMARY KEY IF EXISTS,\n" +
        "    ADD PRIMARY KEY (a, b) NOT ENFORCED,\n" +
        "    ADD CONSTRAINT fk FOREIGN KEY (c) REFERENCES o(c) NOT ENFORCED;\n}",
    );
    expect(many).to.contain("--   ADD PRIMARY KEY (a, b),");
    expect(many).to.contain("--   ADD CONSTRAINT fk FOREIGN KEY (c) REFERENCES o(c);");
    expect(many).to.not.contain("DROP PRIMARY KEY");

    // An ALTER TABLE with no NOT ENFORCED is left exactly as it was.
    const plain = sql("select 1 as id\npost_operations {\n  ALTER TABLE t ADD COLUMN x int;\n}");
    expect(plain).to.contain("ALTER TABLE t ADD COLUMN x int;");
    expect(plain).to.not.contain("-- ALTER TABLE");
  });

  test("lexical rules leave js regions alone — there, quotes are JavaScript", () => {
    // A backtick opens a template literal and a double quote a JS string; rewriting either as
    // SQL quoting produces a file that no longer parses as JavaScript.
    const withJs = convertTarget(
      'config { type: "view" }\n\njs {\n  const t = `SELECT "x" FROM y`;\n}\n\nselect 1\n',
      false,
    ).content;
    expect(withJs).to.contain('const t = `SELECT "x" FROM y`;');

    // Same for a whole .js file (jsMode).
    const asJs = convertTarget('const q = `SELECT "a" FROM t`;\n', true).content;
    expect(asJs).to.contain('`SELECT "a" FROM t`');

    // And inside a ${...} interpolation, which is JavaScript too. Rewriting ref("x") to ref('x')
    // happens to stay valid JS — which is exactly why it must be excluded deliberately rather
    // than by luck, since a name containing an apostrophe would not survive it.
    const withRef = convertTarget(
      'config { type: "view" }\n\nselect 1 from ${ref("orders")}\n',
      false,
    ).content;
    expect(withRef).to.contain('${ref("orders")}');
  });
});
