#!/bin/bash

####################################################################################################
# Generate documentation for the Javascript API.
####################################################################################################

# Docs now live in the separate SQLAnvil/docs repo. Clone it as a sibling of this
# repo (../docs) before regenerating, or override with DOCS_REPO.
#   git clone git@github.com:sqlanvil/docs.git ../docs
DOCS_REPO="${DOCS_REPO:-../docs}"
REF_DIR="${DOCS_REPO}/reference"

if [ ! -d "${REF_DIR}" ]; then
  echo "ERROR: ${REF_DIR} not found. Clone the docs repo: git clone git@github.com:sqlanvil/docs.git ${DOCS_REPO}"
  exit 1
fi

npx typedoc

mv newdocs/classes/_core_session_.session.md "${REF_DIR}/session.md"
mv newdocs/classes/_core_actions_assertion_.assertion.md "${REF_DIR}/assertion.md"
mv newdocs/classes/_core_actions_table_.table.md "${REF_DIR}/table.md"
mv newdocs/classes/_core_actions_declaration_.declaration.md "${REF_DIR}/declaration.md"
mv newdocs/classes/_core_actions_incremental_table_.incrementaltable.md "${REF_DIR}/incrementaltable.md"
mv newdocs/classes/_core_actions_notebook_.notebook.md "${REF_DIR}/notebook.md"
mv newdocs/classes/_core_actions_operation_.operation.md "${REF_DIR}/operation.md"
mv newdocs/classes/_core_actions_test_.test.md "${REF_DIR}/test.md"
mv newdocs/classes/_core_actions_view_.view.md "${REF_DIR}/view.md"

rm -rf newdocs

####################################################################################################
# Generate documentation for protobufs.
####################################################################################################

# docker pull pseudomuto/protoc-gen-doc

# docker run --rm \
#     -v $(pwd)/docs:/out \
#     -v $(pwd)/protos:/protos \
#     pseudomuto/protoc-gen-doc configs.proto --doc_opt=markdown,configs-reference.md::camel_case_fields=true

echo ERROR: Generating docs with camel casing requires https://github.com/pseudomuto/protoc-gen-doc/pull/540 to be merged.
echo Until this is merged, the updated image with camel casing can be built from the fork before running the above script.
echo This can be done via:
echo $ git clone git@github.com:Ekrekr/protoc-gen-doc.git
echo $ make dev/docker
echo then uncommenting the "docker run" part of this script, and commenting the failure exit return code and prior warning.
exit 1
